apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pyappflasktest
  namespace: apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pyappflasktest
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 50
#  - type: Resource
#    resource:
#      name: memory
#      target:
#        type: AverageValue
#        averageValue: 100Mi