apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyappflasktest
  namespace: apps
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: "50%"
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pyappflasktest
  template:
    metadata:
      labels:
        app: pyappflasktest
    spec:
      containers:
      - image: roanfranklin/pyappflasktest:latest
        name: pyappflasktest
        env:
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: pyappflasktest-configmap
                key: DEBUG
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: pyappflasktest-configmap
                key: MYSQL_HOST
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: pyappflasktest-configmap
                key: MYSQL_DATABASE
          - name: MYSQL_USERNAME
            valueFrom:
              configMapKeyRef:
                name: pyappflasktest-configmap
                key: MYSQL_USERNAME
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
