apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplewhale
  namespace: apps
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simplewhale
  template:
    metadata:
      labels:
        app: simplewhale
    spec:
      containers:
      - image: roanfranklin/simplewhale:latest
        name: simplewhale
        ports:
        - containerPort: 80
