apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logging-filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
    task: logging
spec:
  template:
    metadata:
      labels:
        k8s-app: filebeat
        task: logging
      name: logging-filebeat
    spec:
      containers:
      - name: filebeat
        image: schikin/filebeat:5.5
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        env:
        - name: FILEBEAT_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: varlog
          mountPath: /var/log/containers
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /config
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/containers
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: filebeat-config
