apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: kube-system
  labels:
    k8s-app: kibana
    task: logging
data:
    kibana.yml: |
      server.port: 5601
      server.host: "0.0.0.0"
      server.basePath: ""
      elasticsearch.url: "http://logging-elasticsearch.kube-system:9200"
      kibana.index: ".kibana"
      kibana.defaultAppId: "discover"
      elasticsearch.ssl.verificationMode: none
      elasticsearch.pingTimeout: 1500
      elasticsearch.requestTimeout: 30000
      logging.dest: stdout
      logging.verbose: false
      ops.interval: 5000
      i18n.defaultLocale: "en"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logging-kibana
  namespace: kube-system
  labels:
    k8s-app: kibana
    task: logging
spec:
  template:
    metadata:
      labels:
        k8s-app: kibana
        task: logging
      name: logging-kibana
    spec:
      containers:
      - name: kibana
        image: schikin/kibana:5.5
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: kibana-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kibana
    task: logging
  name: logging-kibana
  namespace: kube-system
spec:
  ports:
  - port: 5601
    targetPort: 5601
    name: http
  selector:
    k8s-app: kibana
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: kube-system
  labels:
    task: logging
    k8s-app: kibana
spec:
  rules:
  - host: kibana.foo.bar
    http:
      paths:
      - backend:
          serviceName: logging-kibana
          servicePort: 5601
