apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: kube-system
  labels:
    k8s-app: kibana
    task: logging
data:
    kibana.yml: |
      server.port: 5601
      server.host: "0.0.0.0"
      server.basePath: ""
      elasticsearch.url: "http://logging-elasticsearch.kube-system:9200"
      kibana.index: ".kibana"
      kibana.defaultAppId: "discover"
      elasticsearch.ssl.verificationMode: none
      elasticsearch.pingTimeout: 1500
      elasticsearch.requestTimeout: 30000
      logging.dest: stdout
      logging.verbose: false
      ops.interval: 5000
      i18n.defaultLocale: "en"
